export const images ={
    iosImage : require('../Assets/Png/IosImage.png'),
    Facebook : require('../Assets/Png/Facebook.png'),
    Google : require('../Assets/Png/Google.png'),
    SentMail : require('../Assets/Png/SentMail.png'),
    dummyImage   : require('../Assets/Png/SentMail.png'),
    arrowleft : require('../Assets/Png/arrowleft.png'),
    Profile : require('../Assets/Png/profile.png'),
    Receipt : require('../Assets/Png/Receipt.png'),
    Notification : require('../Assets/Png/Notification.png'),
    Home: require('../Assets/Png/Home.png'),
    ProfileHeader: require('../Assets/Png/ProfileHeader.png'),
    Hoddie: require('../Assets/Png/Hoddie.png'),
    Accessories: require('../Assets/Png/Accessories.png'),
    Bag: require('../Assets/Png/Bag.png'),
    Shoes: require('../Assets/Png/Shoes.png'),
    Shorts: require('../Assets/Png/Shorts.png'),
}
